require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'jpushsoqq' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'jpushsoqqTests' do
    inherit! :complete
    # Pods for testing
  end

   #pod 'JCore', '2.3.6-noidfa'
   #pod 'JPush', '3.2.6'


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'jpushsoqq-tvOS' do
  # Pods for jpushsoqq-tvOS

  target 'jpushsoqq-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
